
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

import java_cup.runtime.*;
import App.*;
import App.Clases.MyStack;
import java.util.*;
import App.Clases.Element;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\023\000\002\002\004\000\002\002\003\000\002\003" +
    "\012\000\002\005\007\000\002\005\006\000\002\004\012" +
    "\000\002\004\010\000\002\004\011\000\002\004\007\000" +
    "\002\010\004\000\002\010\004\000\002\010\004\000\002" +
    "\010\003\000\002\010\003\000\002\010\003\000\002\006" +
    "\005\000\002\006\005\000\002\006\003\000\002\006\003" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\072\000\004\007\004\001\002\000\006\013\012\014" +
    "\011\001\002\000\004\002\000\001\002\000\004\002\007" +
    "\001\002\000\004\002\001\001\002\000\010\005\043\013" +
    "\045\014\044\001\002\000\004\025\031\001\002\000\004" +
    "\012\013\001\002\000\004\014\014\001\002\000\004\025" +
    "\015\001\002\000\004\026\016\001\002\000\012\015\021" +
    "\027\022\030\020\034\023\001\002\000\004\011\030\001" +
    "\002\000\004\006\026\001\002\000\004\011\ufff0\001\002" +
    "\000\004\011\uffef\001\002\000\004\006\024\001\002\000" +
    "\004\034\025\001\002\000\004\011\ufff2\001\002\000\004" +
    "\030\027\001\002\000\004\011\ufff1\001\002\000\010\005" +
    "\ufffa\013\ufffa\014\ufffa\001\002\000\004\026\032\001\002" +
    "\000\010\024\036\032\033\033\035\001\002\000\012\011" +
    "\ufff5\024\ufff5\032\ufff5\033\ufff5\001\002\000\012\011\040" +
    "\024\042\032\037\033\041\001\002\000\012\011\ufff4\024" +
    "\ufff4\032\ufff4\033\ufff4\001\002\000\012\011\ufff3\024\ufff3" +
    "\032\ufff3\033\ufff3\001\002\000\012\011\ufff8\024\ufff8\032" +
    "\ufff8\033\ufff8\001\002\000\010\005\ufff9\013\ufff9\014\ufff9" +
    "\001\002\000\012\011\ufff7\024\ufff7\032\ufff7\033\ufff7\001" +
    "\002\000\012\011\ufff6\024\ufff6\032\ufff6\033\ufff6\001\002" +
    "\000\004\005\060\001\002\000\004\025\054\001\002\000" +
    "\004\012\046\001\002\000\004\014\047\001\002\000\004" +
    "\025\050\001\002\000\004\026\051\001\002\000\012\015" +
    "\021\027\022\030\020\034\023\001\002\000\004\011\053" +
    "\001\002\000\010\005\ufffc\013\ufffc\014\ufffc\001\002\000" +
    "\004\026\055\001\002\000\010\024\036\032\033\033\035" +
    "\001\002\000\012\011\057\024\042\032\037\033\041\001" +
    "\002\000\010\005\ufffb\013\ufffb\014\ufffb\001\002\000\004" +
    "\005\061\001\002\000\004\005\062\001\002\000\004\014" +
    "\064\001\002\000\006\010\070\014\071\001\002\000\004" +
    "\012\065\001\002\000\004\024\066\001\002\000\004\011" +
    "\067\001\002\000\006\010\ufffd\014\ufffd\001\002\000\004" +
    "\002\uffff\001\002\000\004\012\072\001\002\000\004\024" +
    "\073\001\002\000\004\011\074\001\002\000\006\010\ufffe" +
    "\014\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\072\000\006\002\005\003\004\001\001\000\004\004" +
    "\007\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\006\016\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\010\033\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\006\051\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\010\055\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\005\062" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    public int contador=0;
    public void syntax_error(Symbol s)
    {
        System.err.println("Error en la Linea " + (s.right+1) +" Columna "+(s.left+1)+ ". Identificador "+s.value + " no reconocido. Se ha recuperado del error." );
    }
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
    {
        System.err.println("Error en la Linea " + (s.right+1)+ " Columna "+(s.left+1)+". Identificador " +s.value + " no reconocido.");
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= EXP 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // EXP ::= Llave_a DECLARACION Cierre Cierre Cierre Cierre SENTENCIA Llave_c 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXP",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // SENTENCIA ::= SENTENCIA palabra Dos_p Cadena P_coma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // SENTENCIA ::= palabra Dos_p Cadena P_coma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENTENCIA",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // DECLARACION ::= DECLARACION conj Dos_p palabra Menos Mayor NOTACION P_coma 
            {
              Object RESULT =null;
		App.Principal.Reconocido.ConvertToInfix(App.Principal.Characters.getPila()); parser.contador=0;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // DECLARACION ::= DECLARACION palabra Menos Mayor REG P_coma 
            {
              Object RESULT =null;
		App.Principal.Reconocido.ConvertToInfix(App.Principal.Characters.getPila()); parser.contador=0;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // DECLARACION ::= conj Dos_p palabra Menos Mayor NOTACION P_coma 
            {
              Object RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // DECLARACION ::= palabra Menos Mayor REG P_coma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // REG ::= REG Operador 
            {
              Object RESULT =null;
		int operadorleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int operadorright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String operador = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		App.Principal.Characters.InsertInStack(new Element(operador,"operador",parser.contador));
              CUP$parser$result = parser.getSymbolFactory().newSymbol("REG",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // REG ::= REG ExpReg 
            {
              Object RESULT =null;
		int conjuntoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int conjuntoright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String conjunto = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		App.Principal.Characters.InsertInStack(new Element(conjunto,"conjunto",parser.contador));
              CUP$parser$result = parser.getSymbolFactory().newSymbol("REG",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // REG ::= REG Cadena 
            {
              Object RESULT =null;
		int cadenaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cadenaright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String cadena = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		App.Principal.Characters.InsertInStack(new Element(cadena,"cadena",parser.contador));
              CUP$parser$result = parser.getSymbolFactory().newSymbol("REG",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // REG ::= Operador 
            {
              Object RESULT =null;
		int operadorleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int operadorright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String operador = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		App.Principal.Characters.InsertInStack(new Element(operador,"operador",parser.contador));
              CUP$parser$result = parser.getSymbolFactory().newSymbol("REG",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // REG ::= ExpReg 
            {
              Object RESULT =null;
		int conjuntoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int conjuntoright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String conjunto = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		App.Principal.Characters.InsertInStack(new Element(conjunto,"conjunto",parser.contador));
              CUP$parser$result = parser.getSymbolFactory().newSymbol("REG",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // REG ::= Cadena 
            {
              Object RESULT =null;
		int cadenaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cadenaright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String cadena = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		App.Principal.Characters.InsertInStack(new Element(cadena,"cadena",parser.contador));
              CUP$parser$result = parser.getSymbolFactory().newSymbol("REG",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // NOTACION ::= D Virgulilla D 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("NOTACION",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // NOTACION ::= L Virgulilla L 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("NOTACION",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // NOTACION ::= Lista 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("NOTACION",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // NOTACION ::= Lista_letras 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("NOTACION",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
