
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Virgulilla = 4;
  public static final int Dos_p = 8;
  public static final int ExpReg = 25;
  public static final int Cierre = 3;
  public static final int Mas = 15;
  public static final int numero = 23;
  public static final int Mayor = 20;
  public static final int conj = 9;
  public static final int L = 22;
  public static final int Llave_c = 6;
  public static final int Llave_a = 5;
  public static final int Coma = 2;
  public static final int P_coma = 7;
  public static final int Asterisco = 14;
  public static final int D = 26;
  public static final int Operador = 24;
  public static final int Cadena = 18;
  public static final int Reg = 17;
  public static final int EOF = 0;
  public static final int Lista = 11;
  public static final int Interrogacion = 16;
  public static final int palabra = 10;
  public static final int error = 1;
  public static final int Menos = 19;
  public static final int Punto = 13;
  public static final int Lista_letras = 21;
  public static final int Pipe = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Coma",
  "Cierre",
  "Virgulilla",
  "Llave_a",
  "Llave_c",
  "P_coma",
  "Dos_p",
  "conj",
  "palabra",
  "Lista",
  "Pipe",
  "Punto",
  "Asterisco",
  "Mas",
  "Interrogacion",
  "Reg",
  "Cadena",
  "Menos",
  "Mayor",
  "Lista_letras",
  "L",
  "numero",
  "Operador",
  "ExpReg",
  "D"
  };
}

